// Package ports declares external service boundaries used by the application.
package ports

import (
	"context"
	"encoding/json"
	"errors"
	"time"
)

// InitializePayment contains provider-neutral checkout initialization data.
type InitializePayment struct {
	Reference   string
	Email       string
	AmountKobo  int64
	Currency    string
	CallbackURL string
	Metadata    map[string]string
}

// Checkout is returned by a gateway after it creates a hosted checkout.
type Checkout struct {
	Reference string
	URL       string
}

// Verification is the normalized result of a server-side gateway verification.
type Verification struct {
	Reference  string
	Status     string
	AmountKobo int64
	Currency   string
	Domain     string
	Channel    string
	Metadata   map[string]string
	PaidAt     *time.Time
	Message    string
}

// GatewayWebhook is a validated and normalized payment provider event.
type GatewayWebhook struct {
	Event     string
	Reference string
	Raw       json.RawMessage
}

// PaymentGateway isolates the domain from a specific payment provider.
type PaymentGateway interface {
	Initialize(context.Context, InitializePayment) (Checkout, error)
	Verify(context.Context, string, int64) (Verification, error)
	ValidateWebhook(body []byte, signature string) (GatewayWebhook, error)
}

// TransferInstruction is a dynamic virtual account (DVA) generated by the
// gateway so a customer can pay by bank transfer.
type TransferInstruction struct {
	AccountNumber string
	AccountName   string
	BankName      string
	Reference     string // gateway-side reference to requery for completion
	ExpiresAt     time.Time
	ValidityMins  int
}

// TransferGateway is implemented by gateways that can generate dynamic virtual
// accounts for bank-transfer collection (Interswitch DVA).
type TransferGateway interface {
	Transfer(context.Context, InitializePayment) (TransferInstruction, error)
}

// InteractiveMessage describes a message with reply buttons or a list.
type InteractiveMessage struct {
	To          string
	Body        string
	ButtonLabel string
	Sections    []InteractiveSection
	Buttons     []InteractiveButton
}

// InteractiveSection groups options in a WhatsApp list.
type InteractiveSection struct {
	Title string
	Rows  []InteractiveRow
}

// InteractiveRow is one selectable WhatsApp list item.
type InteractiveRow struct {
	ID          string
	Title       string
	Description string
}

// InteractiveButton is one WhatsApp reply button.
type InteractiveButton struct {
	ID    string
	Title string
}

// Messenger isolates conversation behavior from WhatsApp's wire format.
type Messenger interface {
	SendText(context.Context, string, string) error
	SendInteractive(context.Context, InteractiveMessage) error
	SendCheckout(context.Context, string, string, string) error
	// SendLink sends a call-to-action URL message with a custom button label.
	// Web flows use it for the single link message that starts a browser flow.
	SendLink(context.Context, string, string, string, string) error
	SendTemplate(context.Context, string, string, []string) error
	SendImage(ctx context.Context, to string, imageData []byte, caption string) error
}

// EmailSender sends transactional onboarding and receipt email messages.
type EmailSender interface {
	Send(context.Context, string, string, string) error
}

// DataFulfilmentRequest contains the data-bundle order details sent to a data provider.
type DataFulfilmentRequest struct {
	OrderID           string
	RequestCode       string
	ProviderReference string
	NetworkCode       string
	PlanCode          string
	ProviderSKU       string
	BeneficiaryPhone  string
	AmountKobo        int64
}

// DataFulfilmentResult is the provider-neutral result of a data-bundle request.
type DataFulfilmentResult struct {
	ProviderReference string
	Status            string
	Message           string
}

// DataProvider isolates Xego data sales from a specific VTU or network API.
type DataProvider interface {
	FulfilData(context.Context, DataFulfilmentRequest) (DataFulfilmentResult, error)
	CheckDataStatus(context.Context, string) (DataFulfilmentResult, error)
}

// IdentityVerificationRequest contains the customer details sent to an
// identity verification provider.
type IdentityVerificationRequest struct {
	IDType      string
	IDNumber    string
	LegalName   string
	DateOfBirth string
	PhoneNumber string
}

// IdentityVerificationResult is the provider-neutral outcome of an identity
// check.
type IdentityVerificationResult struct {
	Status      string
	ProviderRef string
	MatchName   bool
	MatchDOB    bool
	Message     string
}

// IdentityVerifier isolates identity verification (NIN/BVN) from a specific
// vendor (Smile ID, Youverify, Dojah, Prembly, ...).
type IdentityVerifier interface {
	VerifyIdentity(context.Context, IdentityVerificationRequest) (IdentityVerificationResult, error)
}

// ScreeningRequest contains the identity details a sanctions/PEP check uses.
type ScreeningRequest struct {
	LegalName   string
	DateOfBirth string
	PhoneNumber string
	Address     string
	CountryCode string
}

// ScreeningDecision is the provider-neutral outcome of a sanctions/PEP check.
type ScreeningDecision struct {
	Decision     string
	MatchedNames []string
	ProviderRef  string
	Message      string
}

// SanctionsScreener isolates name screening from a specific vendor (Smile ID,
// Youverify, Dojah, Prembly, OFAC list, ...).
type SanctionsScreener interface {
	Screen(context.Context, ScreeningRequest) (ScreeningDecision, error)
}

// PayoutRequest contains the neutral payout instruction sent to a bank rail.
type PayoutRequest struct {
	Reference     string // settlement batch_no, used as the idempotency key
	AccountName   string
	AccountNumber string
	BankCode      string
	AmountKobo    int64
	Currency      string
}

// PayoutResult is the provider-neutral outcome of a payout attempt.
type PayoutResult struct {
	ExternalRef string
	Status      string // "succeeded", "failed", "pending"
	Message     string
}

// ErrPayoutPending is returned by a rail when the outcome is not yet final and
// the payout must be rechecked later rather than retried.
var ErrPayoutPending = errors.New("payout outcome pending")

// PayoutProvider isolates outbound settlements from a specific bank rail
// (Interswitch, NIBSS, Providus, ...). Implementations
// must be safe for concurrent use.
type PayoutProvider interface {
	Payout(context.Context, PayoutRequest) (PayoutResult, error)
}

// RefundRequest contains the neutral refund instruction sent to a payment
// provider (Interswitch, etc.).
type RefundRequest struct {
	PaymentID         string // provider reference of the original payment
	PaymentAmountKobo int64  // original payment amount; lets FULL/PARTIAL be derived
	AmountKobo        int64
	Currency          string
}

// RefundResult is the provider-neutral outcome of a refund attempt.
type RefundResult struct {
	Status   string // "succeeded", "failed"
	RefundID string // provider's refund reference
	Message  string
}

// RefundProvider isolates refund processing from a specific payment provider.
// Implementations must be safe for concurrent use.
type RefundProvider interface {
	Refund(context.Context, RefundRequest) (RefundResult, error)
}

// ErrBusClosed is returned when publishing to a closed event bus.
var ErrBusClosed = errors.New("event bus is closed")

// EventMessage is one event published on the event bus. Key is used for
// partition affinity (Kafka-style): all messages with the same key are
// delivered in order to the same partition.
type EventMessage struct {
	Topic   string
	Key     string
	Payload []byte
	Headers map[string]string
}

// EventHandler processes a single event message. It must be idempotent:
// at-least-once delivery means it can be invoked again after a crash.
type EventHandler func(context.Context, EventMessage) error

// EventBus is the Phase 3 event backbone. Every published message must be
// delivered at least once to every consumer group subscribed to its topic.
type EventBus interface {
	Publish(ctx context.Context, msg EventMessage) error
	// Subscribe registers a consumer-group handler for a topic. It starts
	// delivery in the background and keeps delivering until ctx is cancelled.
	Subscribe(ctx context.Context, topic, group string, handler EventHandler) error
	Close() error
}

// ImageReader extracts text from an image. Implementations should handle
// photos of documents (NIN/BVN slips, transfer receipts) and return the
// readable text content.
type ImageReader interface {
	ReadImage(ctx context.Context, imageData []byte, mimeType string, prompt string) (string, error)
}

// SpeechToText transcribes audio bytes into text. Implementations should
// support common voice-note formats (OGG/Opus, MP3, WAV).
type SpeechToText interface {
	Transcribe(ctx context.Context, audioData []byte, mimeType string, language string) (string, error)
}

// ChatAI classifies free-text input into FSM intents and generates
// conversational responses. Implementations must be stateless and fast.
type ChatAI interface {
	// ClassifyIntent maps a user message to one of the known FSM intents.
	// Returns the intent name, extracted entities, and a confidence score.
	ClassifyIntent(ctx context.Context, userMessage string, contextLines []string) (IntentResult, error)
	// Answer generates a conversational response to a question.
	Answer(ctx context.Context, question string, contextLines []string) (string, error)
}

// IntentResult is the outcome of an AI intent classification.
type IntentResult struct {
	Intent     string            `json:"intent"`
	Entities   map[string]string `json:"entities,omitempty"`
	Confidence float64           `json:"confidence"`
}
