package store

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"whatsapp-payment-demo/internal/domain"
	"whatsapp-payment-demo/internal/redact"
)

// DataNetwork is a supported Nigerian mobile network.
type DataNetwork struct {
	ID        uuid.UUID
	Code      string
	Name      string
	Active    bool
	SortOrder int
	CreatedAt time.Time
}

// DataPlan is a sellable mobile data bundle.
type DataPlan struct {
	ID          uuid.UUID
	NetworkID   uuid.UUID
	NetworkCode string
	NetworkName string
	Code        string
	DisplayName string
	DataSize    string
	Validity    string
	PriceKobo   int64
	ProviderSKU string
	Active      bool
	SortOrder   int
	CreatedAt   time.Time
}

// DataOrderView joins a data order with network and plan display fields.
type DataOrderView struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	PaymentID          uuid.NullUUID
	Channel            string
	Recipient          string
	BeneficiaryPhone   string
	NetworkID          uuid.UUID
	NetworkCode        string
	NetworkName        string
	PlanID             uuid.UUID
	PlanCode           string
	PlanName           string
	DataSize           string
	Validity           string
	ProviderSKU        string
	AmountKobo         int64
	Status             domain.DataOrderStatus
	RequestCode        string
	Provider           string
	ProviderReference  string
	FailureReason      string
	UserName           string
	UserEmail          string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	FulfilledAt        *time.Time
	PaymentStatus      domain.PaymentStatus
	PaymentReceipt     string
	PaymentReference   string
	PaymentProvider    string
	PaymentCheckoutURL string
}

// SMSRequestView is one inbound SMS command and the response generated by Xego.
type SMSRequestView struct {
	ID               string
	Sender           string
	Body             string
	Command          string
	RequestCode      string
	ProcessingStatus string
	ResponseBody     string
	ErrorMessage     string
	ReceivedAt       time.Time
	ProcessedAt      *time.Time
}

// ListActiveDataNetworks returns the mobile networks available for data sales.
func (s *Store) ListActiveDataNetworks(ctx context.Context) ([]DataNetwork, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, code, name, active, sort_order, created_at
		FROM data_networks
		WHERE active=true
		ORDER BY sort_order, name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var networks []DataNetwork
	for rows.Next() {
		var network DataNetwork
		if err := rows.Scan(&network.ID, &network.Code, &network.Name, &network.Active, &network.SortOrder, &network.CreatedAt); err != nil {
			return nil, err
		}
		networks = append(networks, network)
	}
	return networks, rows.Err()
}

// DataNetworkByCode resolves an active mobile network by its short code.
func (s *Store) DataNetworkByCode(ctx context.Context, code string) (DataNetwork, error) {
	var network DataNetwork
	err := s.pool.QueryRow(ctx, `
		SELECT id, code, name, active, sort_order, created_at
		FROM data_networks
		WHERE upper(code)=upper($1) AND active=true`, code).Scan(
		&network.ID, &network.Code, &network.Name, &network.Active, &network.SortOrder, &network.CreatedAt,
	)
	return network, err
}

// ListActiveDataPlans returns active plans for one network.
func (s *Store) ListActiveDataPlans(ctx context.Context, networkCode string) ([]DataPlan, error) {
	rows, err := s.pool.Query(ctx, dataPlanSelect()+`
		WHERE n.active=true AND p.active=true AND upper(n.code)=upper($1)
		ORDER BY p.sort_order, p.price_kobo`, networkCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var plans []DataPlan
	for rows.Next() {
		plan, err := scanDataPlan(rows)
		if err != nil {
			return nil, err
		}
		plans = append(plans, plan)
	}
	return plans, rows.Err()
}

// SearchDataPlans returns one customer-facing page of active plans for a network.
func (s *Store) SearchDataPlans(ctx context.Context, networkCode, query string, offset, limit int) ([]DataPlan, bool, error) {
	offset, limit = normalizePageBounds(offset, limit)
	search := strings.ToLower(strings.TrimSpace(query))
	args := []any{limit + 1, offset, networkCode}
	sql := dataPlanSelect() + `
		WHERE n.active=true AND p.active=true AND upper(n.code)=upper($3)`
	if search != "" {
		args = append(args, "%"+search+"%")
		sql += ` AND (
			lower(p.code) LIKE $4 OR lower(p.display_name) LIKE $4 OR
			lower(p.data_size) LIKE $4 OR lower(p.validity) LIKE $4 OR
			lower(p.provider_sku) LIKE $4
		)`
	}
	sql += ` ORDER BY p.sort_order, p.price_kobo, p.display_name LIMIT $1 OFFSET $2`
	rows, err := s.pool.Query(ctx, sql, args...)
	if err != nil {
		return nil, false, err
	}
	defer rows.Close()
	var plans []DataPlan
	for rows.Next() {
		plan, err := scanDataPlan(rows)
		if err != nil {
			return nil, false, err
		}
		plans = append(plans, plan)
	}
	if err := rows.Err(); err != nil {
		return nil, false, err
	}
	hasMore := len(plans) > limit
	if hasMore {
		plans = plans[:limit]
	}
	return plans, hasMore, nil
}

// DataPlanByCode resolves an active sellable data bundle.
func (s *Store) DataPlanByCode(ctx context.Context, planCode string) (DataPlan, error) {
	var plan DataPlan
	err := s.pool.QueryRow(ctx, dataPlanSelect()+`
		WHERE n.active=true AND p.active=true AND upper(p.code)=upper($1)`, planCode).Scan(
		&plan.ID, &plan.NetworkID, &plan.NetworkCode, &plan.NetworkName, &plan.Code,
		&plan.DisplayName, &plan.DataSize, &plan.Validity, &plan.PriceKobo,
		&plan.ProviderSKU, &plan.Active, &plan.SortOrder, &plan.CreatedAt,
	)
	return plan, err
}

// UpsertDataPlanFromProvider inserts or updates one provider catalog plan.
func (s *Store) UpsertDataPlanFromProvider(ctx context.Context, networkCode, code, displayName, dataSize, validity string, priceKobo int64, providerSKU string, sortOrder int) error {
	_, err := s.pool.Exec(ctx, `
		INSERT INTO data_plans (network_id, code, display_name, data_size, validity, price_kobo, provider_sku, active, sort_order)
		SELECT n.id, $2, $3, $4, $5, $6, $7, true, $8
		FROM data_networks n
		WHERE upper(n.code)=upper($1)
		ON CONFLICT (code) DO UPDATE SET
			display_name=EXCLUDED.display_name,
			data_size=EXCLUDED.data_size,
			validity=EXCLUDED.validity,
			price_kobo=EXCLUDED.price_kobo,
			provider_sku=EXCLUDED.provider_sku,
			active=true,
			sort_order=EXCLUDED.sort_order,
			updated_at=now()`,
		networkCode, code, displayName, dataSize, validity, priceKobo, providerSKU, sortOrder)
	return err
}

// XegoDataMerchant returns the internal merchant used to reuse the payment rail.
func (s *Store) XegoDataMerchant(ctx context.Context) (Merchant, error) {
	var merchant Merchant
	err := s.pool.QueryRow(ctx, `
		SELECT id, slug, name, category, description, logo_url, active, search_keywords, sort_order, created_at,
		       password_hash, allow_partial_payments, min_invoice_amount_kobo, upfront_percent,
		       min_installment_percent, max_installments, allow_full_pay_always
		FROM merchants WHERE slug=$1`, "xego-data").Scan(
		&merchant.ID, &merchant.Slug, &merchant.Name, &merchant.Category,
		&merchant.Description, &merchant.LogoURL, &merchant.Active, &merchant.SearchKeywords,
		&merchant.SortOrder, &merchant.CreatedAt,
		&merchant.PasswordHash, &merchant.AllowPartialPayments,
		&merchant.MinInvoiceAmountKobo, &merchant.UpfrontPercent,
		&merchant.MinInstallmentPercent, &merchant.MaxInstallments,
		&merchant.AllowFullPayAlways,
	)
	return merchant, err
}

// CreateDataOrder stores a new draft data purchase with a unique request code.
func (s *Store) CreateDataOrder(ctx context.Context, userID uuid.UUID, channel, recipient, beneficiaryPhone string, plan DataPlan, requestCode string) (DataOrderView, error) {
	id := uuid.New()
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return DataOrderView{}, err
	}
	defer tx.Rollback(ctx)
	if _, err := tx.Exec(ctx, `
		INSERT INTO data_orders
			(id,user_id,channel,recipient,beneficiary_phone,network_id,plan_id,amount_kobo,status,request_code)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,
		id, userID, channel, recipient, beneficiaryPhone, plan.NetworkID, plan.ID, plan.PriceKobo,
		domain.DataOrderDraft, requestCode); err != nil {
		return DataOrderView{}, err
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO data_order_events(data_order_id,from_status,to_status,source)
		VALUES($1,'',$2,'conversation')`, id, domain.DataOrderDraft); err != nil {
		return DataOrderView{}, err
	}
	if err := tx.Commit(ctx); err != nil {
		return DataOrderView{}, err
	}
	return s.DataOrderByID(ctx, id)
}

// AttachDataOrderPayment links a data order to its payment and starts waiting for settlement.
func (s *Store) AttachDataOrderPayment(ctx context.Context, orderID, paymentID uuid.UUID) (DataOrderView, error) {
	if _, err := s.transitionDataOrder(ctx, orderID, domain.DataOrderAwaitingPayment, "payment.created", map[string]any{"payment_id": paymentID.String()}, func(tx pgx.Tx) error {
		_, err := tx.Exec(ctx, `UPDATE data_orders SET payment_id=$2 WHERE id=$1`, orderID, paymentID)
		return err
	}); err != nil {
		return DataOrderView{}, err
	}
	return s.DataOrderByID(ctx, orderID)
}

// DataOrderByID returns one data order with display fields.
func (s *Store) DataOrderByID(ctx context.Context, id uuid.UUID) (DataOrderView, error) {
	return s.dataOrderBy(ctx, "d.id=$1", id)
}

// DataOrderByPaymentID returns the data order linked to a payment.
func (s *Store) DataOrderByPaymentID(ctx context.Context, paymentID uuid.UUID) (DataOrderView, error) {
	return s.dataOrderBy(ctx, "d.payment_id=$1", paymentID)
}

// DataOrderByRequestCode returns the data order used for SMS status checks.
func (s *Store) DataOrderByRequestCode(ctx context.Context, code string) (DataOrderView, error) {
	return s.dataOrderBy(ctx, "upper(d.request_code)=upper($1)", code)
}

// DataOrderByProviderReference resolves an order from a VTPass request id or transaction id.
func (s *Store) DataOrderByProviderReference(ctx context.Context, providerReference string) (DataOrderView, error) {
	return s.dataOrderBy(ctx, "d.provider_reference=$1", providerReference)
}

func (s *Store) dataOrderBy(ctx context.Context, predicate string, value any) (DataOrderView, error) {
	query := dataOrderSelect() + " WHERE " + predicate
	var order DataOrderView
	err := s.pool.QueryRow(ctx, query, value).Scan(dataOrderScanTargets(&order)...)
	return order, err
}

// ListDataOrders returns recent data purchases for the read-only dashboard.
func (s *Store) ListDataOrders(ctx context.Context, limit int) ([]DataOrderView, error) {
	rows, err := s.pool.Query(ctx, dataOrderSelect()+` ORDER BY d.created_at DESC LIMIT $1`, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var orders []DataOrderView
	for rows.Next() {
		var order DataOrderView
		if err := rows.Scan(dataOrderScanTargets(&order)...); err != nil {
			return nil, err
		}
		orders = append(orders, order)
	}
	return orders, rows.Err()
}

// ClaimFulfillableDataOrders leases paid data orders for provider fulfilment.
func (s *Store) ClaimFulfillableDataOrders(ctx context.Context, limit int) ([]DataOrderView, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)
	rows, err := tx.Query(ctx, `
		SELECT d.id
		FROM data_orders d
		JOIN payments p ON p.id=d.payment_id
		WHERE d.status IN ('awaiting_payment','paid') AND p.status='succeeded'
		ORDER BY d.created_at
		FOR UPDATE SKIP LOCKED
		LIMIT $1`, limit)
	if err != nil {
		return nil, err
	}
	var ids []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			rows.Close()
			return nil, err
		}
		ids = append(ids, id)
	}
	rows.Close()
	for _, id := range ids {
		if _, err := s.transitionDataOrderTx(ctx, tx, id, domain.DataOrderPaid, "payment.succeeded", nil, nil); err != nil {
			return nil, err
		}
		if _, err := s.transitionDataOrderTx(ctx, tx, id, domain.DataOrderFulfilling, "data.fulfilment.claim", nil, nil); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	orders := make([]DataOrderView, 0, len(ids))
	for _, id := range ids {
		order, err := s.DataOrderByID(ctx, id)
		if err != nil {
			return nil, err
		}
		orders = append(orders, order)
	}
	return orders, nil
}

// CompleteDataOrderFulfilment records a provider result and queues the customer update.
func (s *Store) CompleteDataOrderFulfilment(ctx context.Context, orderID uuid.UUID, target domain.DataOrderStatus, providerReference, message string, outbox OutboxSpec) error {
	return s.transitionDataOrderWithOutbox(ctx, orderID, target, "data.provider", map[string]any{"provider_reference": providerReference, "message": message}, providerReference, message, outbox)
}

// DeferDataOrderFulfilment stores a pending provider reference, returns the
// order to paid for retry/webhook resolution, and queues one customer
// processing update the first time a provider result is inconclusive.
func (s *Store) DeferDataOrderFulfilment(ctx context.Context, orderID uuid.UUID, providerReference, message string, outbox OutboxSpec) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)
	// The processing notification check cannot run in SQL because payloads are
	// encrypted at rest; decrypt candidate messages and compare in Go.
	var requestCode string
	if err := tx.QueryRow(ctx, `SELECT request_code FROM data_orders WHERE id=$1`, orderID).Scan(&requestCode); err != nil {
		return err
	}
	alreadyNotified := false
	rows, err := tx.Query(ctx, `
		SELECT m.payload
		FROM message_outbox m
		JOIN data_orders d ON d.user_id=m.user_id
		WHERE d.id=$1`, orderID)
	if err != nil {
		return err
	}
	for rows.Next() {
		var sealed string
		if err := rows.Scan(&sealed); err != nil {
			rows.Close()
			return err
		}
		raw, err := s.openValue(sealed)
		if err != nil {
			rows.Close()
			return err
		}
		var body struct {
			Body string `json:"body"`
		}
		if err := json.Unmarshal(raw, &body); err != nil {
			rows.Close()
			return err
		}
		if strings.Contains(body.Body, "Status: PROCESSING") && strings.Contains(body.Body, requestCode) {
			alreadyNotified = true
			break
		}
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return err
	}
	changed, err := s.transitionDataOrderTx(ctx, tx, orderID, domain.DataOrderPaid, "data.provider.pending", map[string]any{"provider_reference": providerReference, "message": message}, func(tx pgx.Tx) error {
		_, err := tx.Exec(ctx, `UPDATE data_orders SET provider_reference=$2, failure_reason='' WHERE id=$1`, orderID, providerReference)
		return err
	})
	if err != nil {
		return err
	}
	if changed && !alreadyNotified && outbox.UserID != uuid.Nil {
		if outbox.Channel == "" {
			outbox.Channel = "whatsapp"
		}
		sealed, err := s.sealValue(outbox.Payload)
		if err != nil {
			return err
		}
		if _, err := tx.Exec(ctx, `
			INSERT INTO message_outbox(user_id,channel,recipient,kind,payload)
			VALUES($1,$2,$3,$4,$5)`, outbox.UserID, outbox.Channel, outbox.Recipient, outbox.Kind, sealed); err != nil {
			return err
		}
	}
	return tx.Commit(ctx)
}

func (s *Store) transitionDataOrder(ctx context.Context, orderID uuid.UUID, to domain.DataOrderStatus, source string, detail map[string]any, extra func(pgx.Tx) error) (bool, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return false, err
	}
	defer tx.Rollback(ctx)
	changed, err := s.transitionDataOrderTx(ctx, tx, orderID, to, source, detail, extra)
	if err != nil {
		return false, err
	}
	return changed, tx.Commit(ctx)
}

func (s *Store) transitionDataOrderWithOutbox(ctx context.Context, orderID uuid.UUID, to domain.DataOrderStatus, source string, detail map[string]any, providerReference, failureReason string, outbox OutboxSpec) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)
	_, err = s.transitionDataOrderTx(ctx, tx, orderID, to, source, detail, func(tx pgx.Tx) error {
		fulfilledClause := ""
		if to == domain.DataOrderFulfilled {
			fulfilledClause = ", fulfilled_at=COALESCE(fulfilled_at, now())"
		}
		_, err := tx.Exec(ctx, `UPDATE data_orders SET provider_reference=$2, failure_reason=$3`+fulfilledClause+` WHERE id=$1`, orderID, providerReference, redact.Error(failureReason, redact.DefaultMaxLen))
		return err
	})
	if err != nil {
		return err
	}
	if outbox.Channel == "" {
		outbox.Channel = "whatsapp"
	}
	sealed, err := s.sealValue(outbox.Payload)
	if err != nil {
		return err
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO message_outbox(user_id,channel,recipient,kind,payload)
		VALUES($1,$2,$3,$4,$5)`, outbox.UserID, outbox.Channel, outbox.Recipient, outbox.Kind, sealed); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

func (s *Store) transitionDataOrderTx(ctx context.Context, tx pgx.Tx, orderID uuid.UUID, to domain.DataOrderStatus, source string, detail map[string]any, extra func(pgx.Tx) error) (bool, error) {
	var from domain.DataOrderStatus
	var amountKobo int64
	if err := tx.QueryRow(ctx, `SELECT status, amount_kobo FROM data_orders WHERE id=$1 FOR UPDATE`, orderID).Scan(&from, &amountKobo); err != nil {
		return false, err
	}
	if from == to {
		return false, nil
	}
	if !domain.CanTransitionDataOrder(from, to) {
		return false, fmt.Errorf("invalid data order transition %s -> %s", from, to)
	}
	raw, err := json.Marshal(detail)
	if err != nil {
		return false, err
	}
	if _, err := tx.Exec(ctx, `UPDATE data_orders SET status=$2, updated_at=now() WHERE id=$1`, orderID, to); err != nil {
		return false, err
	}
	if extra != nil {
		if err := extra(tx); err != nil {
			return false, err
		}
	}
	if to == domain.DataOrderFulfilled {
		// C16: revenue recognition on fulfilment; the customer float (already
		// credited at payment success) is cleared against sales revenue.
		if err := s.postLedgerPair(ctx, tx, orderID.String(), "data_order", orderID.String(),
			LedgerAccountCustomerFloat, LedgerAccountSalesRevenue, "NGN", "Data order revenue recognition", "system", amountKobo, nil); err != nil {
			return false, err
		}
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO data_order_events(data_order_id,from_status,to_status,source,detail)
		VALUES($1,$2,$3,$4,$5)`, orderID, from, to, source, raw); err != nil {
		return false, err
	}
	return true, nil
}

// RecordSMSRequest stores an inbound SMS command and its generated response.
func (s *Store) RecordSMSRequest(ctx context.Context, id, sender, body, command, requestCode, status, responseBody, errorMessage string) (bool, error) {
	tag, err := s.pool.Exec(ctx, `
		INSERT INTO sms_requests(provider_message_id,sender,body,command,request_code,processing_status,response_body,error_message,processed_at)
		VALUES($1,$2,$3,$4,$5,$6,$7,$8,now())
		ON CONFLICT(provider_message_id) DO NOTHING`, id, sender, body, command, requestCode, status, responseBody, errorMessage)
	return tag.RowsAffected() == 1, err
}

// ReserveSMSRequest deduplicates an inbound SMS before any order side effects.
func (s *Store) ReserveSMSRequest(ctx context.Context, id, sender, body string) (bool, SMSRequestView, error) {
	tag, err := s.pool.Exec(ctx, `
		INSERT INTO sms_requests(provider_message_id,sender,body,processing_status)
		VALUES($1,$2,$3,'processing')
		ON CONFLICT(provider_message_id) DO NOTHING`, id, sender, body)
	if err != nil {
		return false, SMSRequestView{}, err
	}
	if tag.RowsAffected() == 1 {
		return true, SMSRequestView{ID: id, Sender: sender, Body: body, ProcessingStatus: "processing"}, nil
	}
	var request SMSRequestView
	err = s.pool.QueryRow(ctx, `
		SELECT provider_message_id,sender,body,command,request_code,processing_status,response_body,error_message,received_at,processed_at
		FROM sms_requests WHERE provider_message_id=$1`, id).Scan(
		&request.ID, &request.Sender, &request.Body, &request.Command, &request.RequestCode,
		&request.ProcessingStatus, &request.ResponseBody, &request.ErrorMessage,
		&request.ReceivedAt, &request.ProcessedAt,
	)
	return false, request, err
}

// CompleteSMSRequest records the command result for operators and duplicate replies.
func (s *Store) CompleteSMSRequest(ctx context.Context, id, command, requestCode, status, responseBody, errorMessage string) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE sms_requests
		SET command=$2,request_code=$3,processing_status=$4,response_body=$5,error_message=$6,processed_at=now()
		WHERE provider_message_id=$1`, id, command, requestCode, status, responseBody, redact.Error(errorMessage, redact.DefaultMaxLen))
	return err
}

// ListSMSRequests returns recent SMS commands for operations review.
func (s *Store) ListSMSRequests(ctx context.Context, limit int) ([]SMSRequestView, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT provider_message_id,sender,body,command,request_code,processing_status,response_body,error_message,received_at,processed_at
		FROM sms_requests ORDER BY received_at DESC LIMIT $1`, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var requests []SMSRequestView
	for rows.Next() {
		var request SMSRequestView
		if err := rows.Scan(&request.ID, &request.Sender, &request.Body, &request.Command, &request.RequestCode, &request.ProcessingStatus, &request.ResponseBody, &request.ErrorMessage, &request.ReceivedAt, &request.ProcessedAt); err != nil {
			return nil, err
		}
		requests = append(requests, request)
	}
	return requests, rows.Err()
}

func dataPlanSelect() string {
	return `
		SELECT p.id, p.network_id, n.code, n.name, p.code, p.display_name, p.data_size,
			p.validity, p.price_kobo, p.provider_sku, p.active, p.sort_order, p.created_at
		FROM data_plans p
		JOIN data_networks n ON n.id=p.network_id `
}

func scanDataPlan(rows pgx.Rows) (DataPlan, error) {
	var plan DataPlan
	err := rows.Scan(
		&plan.ID, &plan.NetworkID, &plan.NetworkCode, &plan.NetworkName, &plan.Code,
		&plan.DisplayName, &plan.DataSize, &plan.Validity, &plan.PriceKobo,
		&plan.ProviderSKU, &plan.Active, &plan.SortOrder, &plan.CreatedAt,
	)
	return plan, err
}

func dataOrderSelect() string {
	return `
		SELECT d.id,d.user_id,d.payment_id,d.channel,d.recipient,d.beneficiary_phone,
			d.network_id,n.code,n.name,d.plan_id,p.code,p.display_name,p.data_size,p.validity,p.provider_sku,
			d.amount_kobo,d.status,d.request_code,d.provider,d.provider_reference,d.failure_reason,
			u.display_name,u.email,d.created_at,d.updated_at,d.fulfilled_at,
			COALESCE(pay.status,''),COALESCE(pay.receipt_token,''),COALESCE(pay.provider_reference,''),
			COALESCE(pay.provider,''),COALESCE(pay.checkout_url,'')
		FROM data_orders d
		JOIN users u ON u.id=d.user_id
		JOIN data_networks n ON n.id=d.network_id
		JOIN data_plans p ON p.id=d.plan_id
		LEFT JOIN payments pay ON pay.id=d.payment_id`
}

func dataOrderScanTargets(order *DataOrderView) []any {
	return []any{
		&order.ID, &order.UserID, &order.PaymentID, &order.Channel, &order.Recipient,
		&order.BeneficiaryPhone, &order.NetworkID, &order.NetworkCode, &order.NetworkName,
		&order.PlanID, &order.PlanCode, &order.PlanName, &order.DataSize, &order.Validity,
		&order.ProviderSKU, &order.AmountKobo, &order.Status, &order.RequestCode,
		&order.Provider, &order.ProviderReference, &order.FailureReason,
		&order.UserName, &order.UserEmail, &order.CreatedAt, &order.UpdatedAt,
		&order.FulfilledAt, &order.PaymentStatus, &order.PaymentReceipt,
		&order.PaymentReference, &order.PaymentProvider, &order.PaymentCheckoutURL,
	}
}
